### PR TITLE
Reconstruct sln/csproj files in VS2017

### PR DESCRIPTION
**Pull request by BruceForstall**
There is some magic here that allows VS2017 to allow better
debugging, e.g., setting of command-line arguments.

### CODE REVIEW

**Comment by BruceForstall** [comment]
@russellhadley @JosephTremoulet PTAL

**Comment by JosephTremoulet** [comment]
- You have different versions of `System.CommandLine` referenced in different csproj's; that needs to be fixed to avoid running into issues like #80 again.
 - The first line in each csproj looks the same to me, but gets highlighted in the github diff view.  Is there a BOM or a non-ascii quote or different line ending or something?  I guess it doesn't matter as long as restore/build/publish still work on all platforms.

**Comment by BruceForstall** [comment]
There is a BOM.

I'll check the versions. It was a very manual process trying to get all csproj's to look the same.

**Comment by BruceForstall** [comment]
@JosephTremoulet updated. Also, tested on Mac OSX and Ubuntu 16.04 -- seems to work.

**Pull request merged**
