### PR TITLE
AnalyzeAsm analysis and print assembly

### PR DESCRIPTION
**Pull request by kunalspathak**
* Added following analyzer:
  *  FindPreIndexAddrMode
  * Find ldr followed by str or vice-versa

* Added ability to find assembly method in output produced by jit-analyze. It creates a `.index` file containing method names along with start/end line of that method in all the files. Subsequent lookups are quick. Again the folder paths are hardcoded but can be easily made to be passed via command line.

### CODE REVIEW

**Comment by kunalspathak** [comment]
@BruceForstall

**Comment by BruceForstall** [comment]
Great additions. No need for a code review (I didn't review the code), since it's a tool that only you are using right now. I'll just point out that "occurance" is properly spelled "occurrence".

**Comment by kunalspathak** [comment]
Ah, thanks, fixed it.

**Comment by kunalspathak** [comment]
Hhm, I should have squashed the commits before merging.

**Pull request merged**
