### PR TITLE
Include ASP.NET Core in packages

### PR DESCRIPTION
**Pull request by benaadams**
Not sure if just changing the Project type will work?

Resolves https://github.com/dotnet/jitutils/issues/189

/cc @AndyAyersMS  @mikedn

### CODE REVIEW

**Comment by benaadams** [comment]
`bootstrap.cmd` adds the following dlls (including ASP.NET Core's) to `jitutils\fx` is that all that needs to happen?

```
api-ms-win-core-console-l1-1-0.dll
api-ms-win-core-datetime-l1-1-0.dll
api-ms-win-core-debug-l1-1-0.dll
api-ms-win-core-errorhandling-l1-1-0.dll
api-ms-win-core-file-l1-1-0.dll
api-ms-win-core-file-l1-2-0.dll
api-ms-win-core-file-l2-1-0.dll
api-ms-win-core-handle-l1-1-0.dll
api-ms-win-core-heap-l1-1-0.dll
api-ms-win-core-interlocked-l1-1-0.dll
api-ms-win-core-libraryloader-l1-1-0.dll
api-ms-win-core-localization-l1-2-0.dll
api-ms-win-core-memory-l1-1-0.dll
api-ms-win-core-namedpipe-l1-1-0.dll
api-ms-win-core-processenvironment-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-0.dll
api-ms-win-core-processthreads-l1-1-1.dll
api-ms-win-core-profile-l1-1-0.dll
api-ms-win-core-rtlsupport-l1-1-0.dll
api-ms-win-core-string-l1-1-0.dll
api-ms-win-core-synch-l1-1-0.dll
api-ms-win-core-synch-l1-2-0.dll
api-ms-win-core-sysinfo-l1-1-0.dll
api-ms-win-core-timezone-l1-1-0.dll
api-ms-win-core-util-l1-1-0.dll
api-ms-win-crt-conio-l1-1-0.dll
api-ms-win-crt-convert-l1-1-0.dll
api-ms-win-crt-environment-l1-1-0.dll
api-ms-win-crt-filesystem-l1-1-0.dll
api-ms-win-crt-heap-l1-1-0.dll
api-ms-win-crt-locale-l1-1-0.dll
api-ms-win-crt-math-l1-1-0.dll
api-ms-win-crt-multibyte-l1-1-0.dll
api-ms-win-crt-private-l1-1-0.dll
api-ms-win-crt-process-l1-1-0.dll
api-ms-win-crt-runtime-l1-1-0.dll
api-ms-win-crt-stdio-l1-1-0.dll
api-ms-win-crt-string-l1-1-0.dll
api-ms-win-crt-time-l1-1-0.dll
api-ms-win-crt-utility-l1-1-0.dll
aspnetcorev2_inprocess.dll
clrcompression.dll
clretwrc.dll
clrjit.dll
coreclr.dll
dbgshim.dll
hostfxr.dll
hostpolicy.dll
Microsoft.AspNetCore.Antiforgery.dll
Microsoft.AspNetCore.Authentication.Abstractions.dll
Microsoft.AspNetCore.Authentication.Cookies.dll
Microsoft.AspNetCore.Authentication.Core.dll
Microsoft.AspNetCore.Authentication.dll
Microsoft.AspNetCore.Authentication.OAuth.dll
Microsoft.AspNetCore.Authorization.dll
Microsoft.AspNetCore.Authorization.Policy.dll
Microsoft.AspNetCore.Components.Browser.dll
Microsoft.AspNetCore.Components.dll
Microsoft.AspNetCore.Connections.Abstractions.dll
Microsoft.AspNetCore.CookiePolicy.dll
Microsoft.AspNetCore.Cors.dll
Microsoft.AspNetCore.Cryptography.Internal.dll
Microsoft.AspNetCore.Cryptography.KeyDerivation.dll
Microsoft.AspNetCore.DataProtection.Abstractions.dll
Microsoft.AspNetCore.DataProtection.dll
Microsoft.AspNetCore.DataProtection.Extensions.dll
Microsoft.AspNetCore.Diagnostics.Abstractions.dll
Microsoft.AspNetCore.Diagnostics.dll
Microsoft.AspNetCore.Diagnostics.HealthChecks.dll
Microsoft.AspNetCore.dll
Microsoft.AspNetCore.HostFiltering.dll
Microsoft.AspNetCore.Hosting.Abstractions.dll
Microsoft.AspNetCore.Hosting.dll
Microsoft.AspNetCore.Hosting.Server.Abstractions.dll
Microsoft.AspNetCore.Html.Abstractions.dll
Microsoft.AspNetCore.Http.Abstractions.dll
Microsoft.AspNetCore.Http.Connections.Common.dll
Microsoft.AspNetCore.Http.Connections.dll
Microsoft.AspNetCore.Http.dll
Microsoft.AspNetCore.Http.Extensions.dll
Microsoft.AspNetCore.Http.Features.dll
Microsoft.AspNetCore.HttpOverrides.dll
Microsoft.AspNetCore.HttpsPolicy.dll
Microsoft.AspNetCore.Identity.dll
Microsoft.AspNetCore.Localization.dll
Microsoft.AspNetCore.Localization.Routing.dll
Microsoft.AspNetCore.Mvc.Abstractions.dll
Microsoft.AspNetCore.Mvc.ApiExplorer.dll
Microsoft.AspNetCore.Mvc.Core.dll
Microsoft.AspNetCore.Mvc.Cors.dll
Microsoft.AspNetCore.Mvc.DataAnnotations.dll
Microsoft.AspNetCore.Mvc.dll
Microsoft.AspNetCore.Mvc.Formatters.Json.dll
Microsoft.AspNetCore.Mvc.Formatters.Xml.dll
Microsoft.AspNetCore.Mvc.Localization.dll
Microsoft.AspNetCore.Mvc.Razor.dll
Microsoft.AspNetCore.Mvc.RazorPages.dll
Microsoft.AspNetCore.Mvc.TagHelpers.dll
Microsoft.AspNetCore.Mvc.ViewFeatures.dll
Microsoft.AspNetCore.Razor.dll
Microsoft.AspNetCore.Razor.Runtime.dll
Microsoft.AspNetCore.ResponseCaching.Abstractions.dll
Microsoft.AspNetCore.ResponseCaching.dll
Microsoft.AspNetCore.ResponseCompression.dll
Microsoft.AspNetCore.Rewrite.dll
Microsoft.AspNetCore.Routing.Abstractions.dll
Microsoft.AspNetCore.Routing.dll
Microsoft.AspNetCore.Server.HttpSys.dll
Microsoft.AspNetCore.Server.IIS.dll
Microsoft.AspNetCore.Server.IISIntegration.dll
Microsoft.AspNetCore.Server.Kestrel.Core.dll
Microsoft.AspNetCore.Server.Kestrel.dll
Microsoft.AspNetCore.Server.Kestrel.Transport.Abstractions.dll
Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.dll
Microsoft.AspNetCore.Session.dll
Microsoft.AspNetCore.SignalR.Common.dll
Microsoft.AspNetCore.SignalR.Core.dll
Microsoft.AspNetCore.SignalR.dll
Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson.dll
Microsoft.AspNetCore.StaticFiles.dll
Microsoft.AspNetCore.WebSockets.dll
Microsoft.AspNetCore.WebUtilities.dll
Microsoft.CSharp.dll
Microsoft.DiaSymReader.Native.amd64.dll
Microsoft.DotNet.PlatformAbstractions.dll
Microsoft.Extensions.Caching.Abstractions.dll
Microsoft.Extensions.Caching.Memory.dll
Microsoft.Extensions.Configuration.Abstractions.dll
Microsoft.Extensions.Configuration.Binder.dll
Microsoft.Extensions.Configuration.CommandLine.dll
Microsoft.Extensions.Configuration.dll
Microsoft.Extensions.Configuration.EnvironmentVariables.dll
Microsoft.Extensions.Configuration.FileExtensions.dll
Microsoft.Extensions.Configuration.Ini.dll
Microsoft.Extensions.Configuration.Json.dll
Microsoft.Extensions.Configuration.KeyPerFile.dll
Microsoft.Extensions.Configuration.UserSecrets.dll
Microsoft.Extensions.Configuration.Xml.dll
Microsoft.Extensions.DependencyInjection.Abstractions.dll
Microsoft.Extensions.DependencyInjection.dll
Microsoft.Extensions.DependencyModel.dll
Microsoft.Extensions.Diagnostics.HealthChecks.Abstractions.dll
Microsoft.Extensions.Diagnostics.HealthChecks.dll
Microsoft.Extensions.FileProviders.Abstractions.dll
Microsoft.Extensions.FileProviders.Composite.dll
Microsoft.Extensions.FileProviders.Embedded.dll
Microsoft.Extensions.FileProviders.Physical.dll
Microsoft.Extensions.FileSystemGlobbing.dll
Microsoft.Extensions.Hosting.Abstractions.dll
Microsoft.Extensions.Hosting.dll
Microsoft.Extensions.Http.dll
Microsoft.Extensions.Identity.Core.dll
Microsoft.Extensions.Identity.Stores.dll
Microsoft.Extensions.Localization.Abstractions.dll
Microsoft.Extensions.Localization.dll
Microsoft.Extensions.Logging.Abstractions.dll
Microsoft.Extensions.Logging.Configuration.dll
Microsoft.Extensions.Logging.Console.dll
Microsoft.Extensions.Logging.Debug.dll
Microsoft.Extensions.Logging.dll
Microsoft.Extensions.Logging.EventSource.dll
Microsoft.Extensions.Logging.TraceSource.dll
Microsoft.Extensions.ObjectPool.dll
Microsoft.Extensions.Options.ConfigurationExtensions.dll
Microsoft.Extensions.Options.DataAnnotations.dll
Microsoft.Extensions.Options.dll
Microsoft.Extensions.Primitives.dll
Microsoft.Extensions.WebEncoders.dll
Microsoft.JSInterop.dll
Microsoft.Net.Http.Headers.dll
Microsoft.VisualBasic.Core.dll
Microsoft.VisualBasic.dll
Microsoft.Win32.Primitives.dll
Microsoft.Win32.Registry.dll
mscordaccore.dll
mscordaccore_amd64_amd64_4.6.27418.71.dll
mscordbi.dll
mscorrc.debug.dll
mscorrc.dll
netstandard.dll
Newtonsoft.Json.dll
packages.dll
sos.dll
SOS.NETCore.dll
sos_amd64_amd64_4.6.27418.71.dll
System.AppContext.dll
System.Buffers.dll
System.Collections.Concurrent.dll
System.Collections.dll
System.Collections.Immutable.dll
System.Collections.NonGeneric.dll
System.Collections.Specialized.dll
System.ComponentModel.Annotations.dll
System.ComponentModel.DataAnnotations.dll
System.ComponentModel.dll
System.ComponentModel.EventBasedAsync.dll
System.ComponentModel.Primitives.dll
System.ComponentModel.TypeConverter.dll
System.Configuration.dll
System.Console.dll
System.Core.dll
System.Data.Common.dll
System.Data.dll
System.Diagnostics.Contracts.dll
System.Diagnostics.Debug.dll
System.Diagnostics.DiagnosticSource.dll
System.Diagnostics.FileVersionInfo.dll
System.Diagnostics.Process.dll
System.Diagnostics.StackTrace.dll
System.Diagnostics.TextWriterTraceListener.dll
System.Diagnostics.Tools.dll
System.Diagnostics.TraceSource.dll
System.Diagnostics.Tracing.dll
System.dll
System.Drawing.dll
System.Drawing.Primitives.dll
System.Dynamic.Runtime.dll
System.Globalization.Calendars.dll
System.Globalization.dll
System.Globalization.Extensions.dll
System.IO.Compression.Brotli.dll
System.IO.Compression.dll
System.IO.Compression.FileSystem.dll
System.IO.Compression.ZipFile.dll
System.IO.dll
System.IO.FileSystem.AccessControl.dll
System.IO.FileSystem.dll
System.IO.FileSystem.DriveInfo.dll
System.IO.FileSystem.Primitives.dll
System.IO.FileSystem.Watcher.dll
System.IO.IsolatedStorage.dll
System.IO.MemoryMappedFiles.dll
System.IO.Pipelines.dll
System.IO.Pipes.AccessControl.dll
System.IO.Pipes.dll
System.IO.UnmanagedMemoryStream.dll
System.Linq.dll
System.Linq.Expressions.dll
System.Linq.Parallel.dll
System.Linq.Queryable.dll
System.Memory.dll
System.Net.dll
System.Net.Http.dll
System.Net.HttpListener.dll
System.Net.Mail.dll
System.Net.NameResolution.dll
System.Net.NetworkInformation.dll
System.Net.Ping.dll
System.Net.Primitives.dll
System.Net.Requests.dll
System.Net.Security.dll
System.Net.ServicePoint.dll
System.Net.Sockets.dll
System.Net.WebClient.dll
System.Net.WebHeaderCollection.dll
System.Net.WebProxy.dll
System.Net.WebSockets.Client.dll
System.Net.WebSockets.dll
System.Numerics.dll
System.Numerics.Vectors.dll
System.ObjectModel.dll
System.Private.CoreLib.dll
System.Private.DataContractSerialization.dll
System.Private.Uri.dll
System.Private.Xml.dll
System.Private.Xml.Linq.dll
System.Reflection.DispatchProxy.dll
System.Reflection.dll
System.Reflection.Emit.dll
System.Reflection.Emit.ILGeneration.dll
System.Reflection.Emit.Lightweight.dll
System.Reflection.Extensions.dll
System.Reflection.Metadata.dll
System.Reflection.Primitives.dll
System.Reflection.TypeExtensions.dll
System.Resources.Reader.dll
System.Resources.ResourceManager.dll
System.Resources.Writer.dll
System.Runtime.CompilerServices.Unsafe.dll
System.Runtime.CompilerServices.VisualC.dll
System.Runtime.dll
System.Runtime.Extensions.dll
System.Runtime.Handles.dll
System.Runtime.InteropServices.dll
System.Runtime.InteropServices.RuntimeInformation.dll
System.Runtime.InteropServices.WindowsRuntime.dll
System.Runtime.Intrinsics.dll
System.Runtime.Loader.dll
System.Runtime.Numerics.dll
System.Runtime.Serialization.dll
System.Runtime.Serialization.Formatters.dll
System.Runtime.Serialization.Json.dll
System.Runtime.Serialization.Primitives.dll
System.Runtime.Serialization.Xml.dll
System.Runtime.WindowsRuntime.dll
System.Runtime.WindowsRuntime.UI.Xaml.dll
System.Security.AccessControl.dll
System.Security.Claims.dll
System.Security.Cryptography.Algorithms.dll
System.Security.Cryptography.Cng.dll
System.Security.Cryptography.Csp.dll
System.Security.Cryptography.Encoding.dll
System.Security.Cryptography.OpenSsl.dll
System.Security.Cryptography.Pkcs.dll
System.Security.Cryptography.Primitives.dll
System.Security.Cryptography.X509Certificates.dll
System.Security.Cryptography.Xml.dll
System.Security.dll
System.Security.Permissions.dll
System.Security.Principal.dll
System.Security.Principal.Windows.dll
System.Security.SecureString.dll
System.ServiceModel.Web.dll
System.ServiceProcess.dll
System.Text.Encoding.dll
System.Text.Encoding.Extensions.dll
System.Text.Encodings.Web.dll
System.Text.Json.dll
System.Text.RegularExpressions.dll
System.Threading.Channels.dll
System.Threading.dll
System.Threading.Overlapped.dll
System.Threading.Tasks.Dataflow.dll
System.Threading.Tasks.dll
System.Threading.Tasks.Extensions.dll
System.Threading.Tasks.Parallel.dll
System.Threading.Thread.dll
System.Threading.ThreadPool.dll
System.Threading.Timer.dll
System.Transactions.dll
System.Transactions.Local.dll
System.ValueTuple.dll
System.Web.dll
System.Web.HttpUtility.dll
System.Windows.dll
System.Xml.dll
System.Xml.Linq.dll
System.Xml.ReaderWriter.dll
System.Xml.Serialization.dll
System.Xml.XDocument.dll
System.Xml.XmlDocument.dll
System.Xml.XmlSerializer.dll
System.Xml.XPath.dll
System.Xml.XPath.XDocument.dll
ucrtbase.dll
WindowsBase.dll
```

**Comment by AndyAyersMS** [comment]
It seems like it should work -- you can then pass something like `--assembly jitutils\fx` to `jit-diff` to get it to run on that set.

If this works, it might be nice to have it a shorthand for it in `jit-diffs`. Though it would be looking at some fixed set of ASP.Net sources. Another option is to teach `jit-diffs` about nuget and have it download bits that way.

The builtin `-f` option looks at the assemblies in the test overlay and only processes a subset of those. The "nice" thing about this is that we get something closer to the live CoreFx bits.

**Comment by AndyAyersMS** [comment]
Seems to work plausibly well (w/o your PR):
```
D:\repos\coreclr>jit-diff diff --pmi --diff --assembly d:\repos\jitutils\fx
Using --output D:\repos\coreclr\bin\diffs
Using --diff D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked
Using --arch x64
Using --core_root D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
Beginning PMI Diffs for d:\repos\jitutils\fx
\ Finished 0/0 Base 161/161 Diff [155.0 sec]
Completed PMI Diffs for d:\repos\jitutils\fx in 155.19s
```

**Comment by benaadams** [comment]
With PR
```
C:\GitHub\coreclr>jit-diff diff --pmi --diff --assembly C:\GitHub\jitutils\
Using --output C:\GitHub\coreclr\bin\diffs
Using --diff C:\GitHub\coreclr\bin\Product\Windows_NT.x64.Checked
Using --arch x64
Using --core_root C:\GitHub\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
Beginning PMI Diffs for C:\GitHub\jitutils\
/ Finished 0/0 Base 0/876 Diff
```

**Comment by benaadams** [comment]
> Another option is to teach `jit-diffs` about nuget and have it download bits that way.

dotnet restore on `src/packages/packages.csproj` would probably work too?

**Comment by AndyAyersMS** [comment]
Hmm, I get this with your PR: 289 assys, 3 fail...
```
jit-diff diff --pmi --diff --assembly d:\repos\jitutils\fx
Using --output D:\repos\coreclr\bin\diffs
Using --diff D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked
Using --arch x64
Using --core_root D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
Beginning PMI Diffs for d:\repos\jitutils\fx
/ Finished 0/0 Base 38/289 Diff [28.8 sec]Error running D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe on d:\repos\jitutils\fx\Microsoft.AspNetCore.Mvc.Core.dll
| Finished 0/0 Base 38/289 Diff [28.9 sec]
Dasm command "jit-dasm-pmi --platform D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root --corerun D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe --jit D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked\clrjit.dll --nocopy --output D:\repos\coreclr\bin\diffs\dasmset_12\diff d:\repos\jitutils\fx\Microsoft.AspNetCore.Mvc.Core.dll" returned with 1 failures
\ Finished 0/0 Base 73/289 Diff [57.6 sec]Error running D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe on d:\repos\jitutils\fx\Microsoft.DotNet.PlatformAbstractions.dll
1 errors compiling set.
Dasm command "jit-dasm-pmi --platform D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root --corerun D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe --jit D:\repos\cor- Finished 0/0 Base 73/289 Diff [57.7 sec]" returned with 1 failures D:\repos\coreclr\bin\diffs\dasmset_12\diff d:\repos\jitutils\fx\Microsoft.DotNet.PlatformAbstractions.dll
/ Finished 0/0 Base 90/289 Diff [68.3 sec]Error running D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe on d:\repos\jitutils\fx\Microsoft.Extensions.DependencyModel.dll
1 errors compiling set.
sts\Windows_NT.x64.Release\Tests\Core_Root --corerun D:\repos\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe --jit D:\repos\coreclr\bin\Product\Windows_NT.x64.Checked\clrjit.dll --nocopy --output D:\repos\coreclr\bin\diffs\dasmset_12\diff d:\repos\jitutils\fx\Microsoft.Extensions.DependencyModel.dll" returned with 1 failures
/ Finished 0/0 Base 289/289 Diff [247.0 sec]
Dasm commands returned 0 base failures, 3 diff failures.
Completed PMI Diffs for d:\repos\jitutils\fx in 247.26s
Diffs (if any) can be viewed by comparing: D:\repos\coreclr\bin\diffs\dasmset_12\base D:\repos\coreclr\bin\diffs\dasmset_12\diff
```
Result depends on which SDK you're using to build jituitls; I have 3.0.100-preview4-010309.

Probably would be best if the set of assemblies to test is not tied to the SDK version this way.

**Comment by benaadams** [comment]
I'm doing a delete repo, reclone. Might have had some old stuff in there

**Comment by benaadams** [comment]
Was old stuff in the bin dir from a while ago

> Probably would be best if the set of assemblies to test is not tied to the SDK version this way.

Tried as a `FrameworkReference` but I think that also will tie it to the sdk, changed to `PackageReference` but it tells me not to:

> C:\Program Files\dotnet\sdk\3.0.100-preview4-010378\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.DefaultItems.targets(154,5):
>  warning NETSDK1080: A PackageReference to Microsoft.AspNetCore.App is not necessary when targeting .NET Core 3.0 or higher.
>  If Microsoft.NET.Sdk.Web is used, the shared framework will be referenced automatically.
>  Otherwise, the PackageReference should be replaced with a FrameworkReference. 
> [C:\GitHub\jitutils\src\packages\packages.csproj]

/cc @davidfowl

**Pull request closed without merging**
