### PR TITLE
Support for some simple debug metrics.

### PR DESCRIPTION
**Pull request by AndyAyersMS**
Requires matching change in the jit.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@kunalspathak FYI -- still need to find the matching jit changes.
cc @dotnet/jit-contrib

**Comment by AndyAyersMS** [comment]
Here are the matching jit changes. The only bit I don't like is the need to repeat the method name, as our pattern matching is "stateless". It is somewhat of a requirement as currently we need to handle interleaved disasm output.
```diff
--- a/src/coreclr/src/jit/ee_il_dll.cpp
+++ b/src/coreclr/src/jit/ee_il_dll.cpp
@@ -805,8 +805,20 @@ void Compiler::eeDispVar(ICorDebugInfo::NativeVarInfo* var)
 // Same parameters as ICorStaticInfo::setVars().
 void Compiler::eeDispVars(CORINFO_METHOD_HANDLE ftn, ULONG32 cVars, ICorDebugInfo::NativeVarInfo* vars)
 {
-    printf("*************** Variable debug info\n");
-    printf("%d live ranges\n", cVars);
+    // Estimate number of unique vars with debug info
+    ALLVARSET_TP uniqueVars(AllVarSetOps::MakeEmpty(this));
+    for (unsigned i = 0; i < cVars; i++)
+    {
+        // ignore "special vars" and out of bounds vars
+        if ((((int)vars[i].varNumber) >= 0) && (vars[i].varNumber < lclMAX_ALLSET_TRACKED))
+        {
+            AllVarSetOps::AddElemD(this, uniqueVars, vars[i].varNumber);
+        }
+    }
+
+    printf("; Variable debug info: %d live ranges, %d vars for method %s\n", cVars,
+           AllVarSetOps::Count(this, uniqueVars), info.compFullName);
+
     for (unsigned i = 0; i < cVars; i++)
     {
         eeDispVar(&vars[i]);
```
Generally speaking, I think we should modify the disasm dump in a few ways:
* introduce a "summary" mode that just prints metrics and no details
* introduce a standard header that creates a state transition in the parsers (metrics that follow are for "this method")
* each metric or metric group has a standard intro text `;@Metric` or similar
* introduce a standard footer to trigger a "done " transition in the parser
* prevent record interleaving; likely a simple lock will suffice, though we need to be careful that this gets properly released on failure. Or introduce a standard thread prefix, interlock output at the line level, and require parsers to cope with de-interlacing.

**Comment by kunalspathak** [comment]
Thanks @AndyAyersMS. I can include your debug info changes in my PR that adds instruction count in JIT. We will do a brainstorming about the general "disasm dump changes" and take action based on the outcome.

**Comment by BruceForstall** [comment]
@AndyAyersMS I think your ideas for improved JIT dumping merits its own issue in dotnet/runtime (and perhaps a companion issue here)

**Comment by AndyAyersMS** [comment]
@BruceForstall sure, I'll open one. Some of this thinking dovetails with dotnet/runtime#10462 where we would like to foster a much richer set of metrics, and the tooling to summarize and analyze them.

Also note that we have `jit-decisions-analyze` which leverages eventing to gather stats -- my hope is that the "summary mode" stats would be compact enough that we could consider emitting them as events, and so allow metric collections from release builds.

**Comment by kunalspathak** [comment]
@AndyAyersMS  - "Variable debug info" in `eeDispVars()` is only printed in JITDumps and not in JitDisasm. The metrics are based on JitDisasm. Are you suggesting to include variable debug info for JitDisasm as well?

**Comment by AndyAyersMS** [comment]
It's also emitted via `opts.dspDebugInfo` which maps to `COMPlus_JitDebugDump` which is enabled via  `--debuginfo` in `jit-diff`. So if you want to get debug metrics you need to pass this arg.

Generally we probably want to emit metric info all the time and not just when asked for, provided it is not too expensive to collect and aggregate.

**Comment by kunalspathak** [comment]
https://github.com/dotnet/jitutils/pull/280 contains the changes from this PR. Closing this PR.

**Comment by JulieLeeMSFT** [comment]
> Also note that we have `jit-decisions-analyze` which leverages eventing to gather stats -- my hope is that the "summary mode" stats would be compact enough that we could consider emitting them as events, and so allow metric collections from release builds.

Emitting the "summary mode" from release builds will be very useful. Windows ARM perf team will be able to use those telemetry.

**Pull request closed without merging**
