### PR TITLE
Revert recent .NET upgrade

### PR DESCRIPTION
**Pull request by jakobbotsch**
jitformat pipeline is still using .NET core 3.1. We need to upgrade it in dotnet/runtime before we upgrade jitutils.

### CODE REVIEW

**Comment by jakobbotsch** [comment]
We can maybe just merge https://github.com/dotnet/runtime/pull/77511 instead.

**Review by BruceForstall — APPROVED** [review]

**Comment by BruceForstall** [comment]
> We can maybe just merge [dotnet/runtime#77511](https://github.com/dotnet/runtime/pull/77511) instead.

Might as well wait a few weeks until .NET 7 GA is released?

**Comment by jakobbotsch** [comment]
> Might as well wait a few weeks until .NET 7 GA is released?

I think together with #361 it shouldn't be an issue to take that now.

**Comment by jakobbotsch** [comment]
Hmm, actually I think #361 will not help, but I have changed https://github.com/dotnet/runtime/pull/77511 to upgrade to .NET 6 instead. I think we will need to stay with that until we upgrade jitutils to target .NET 7.

**Comment by jakobbotsch** [comment]
Should not be necessary anymore.

**Pull request closed without merging**
