### PR TITLE
One CoreDisTools NuGet package

### PR DESCRIPTION
**Pull request by echesakovMSFT**
Build one NuGet package that includes all the coredistools binaries.

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib PTAL

**Comment by echesakovMSFT** [comment]
@janvorli This is work on consolidating all coredistools binaries into one package as we discussed a while ago. However, for R2RDump we would still need to add the appropriate MSBuild target in order to copy a library corresponding to the platform it is running on to an appropriate location (next to R2RDump executable).

**Comment by echesakovMSFT** [comment]
@dotnet/jit-contrib ping

**Review by BruceForstall — CHANGES_REQUESTED** [review]
Please remove `src/coredistools/.nuget/.Microsoft.NETCore.CoreDisTools.nuspec.swp` from the change (I presume that's some vim file).

**Comment by echesakovMSFT** [comment]
> Please remove `src/coredistools/.nuget/.Microsoft.NETCore.CoreDisTools.nuspec.swp` from the change (I presume that's some vim file).

Done, thanks for catching this - it's indeed a vim file.

**Review by BruceForstall — APPROVED** [review]

**Pull request merged**
