### PR TITLE
Rename protononjit.dll to clrjit_win_arm64_x64.dll

### PR DESCRIPTION
**Pull request by kunalspathak**
Now that we have stopped producing `protononjit.dll` in https://github.com/dotnet/runtime/pull/41126, replace its reference with new name e.g. `clrjit_win_arm64_x64.dll`

### CODE REVIEW

**Comment by kunalspathak** [comment]
@dotnet/jit-contrib

**Review by BruceForstall — APPROVED** [review]

**Comment by kunalspathak** [comment]
Thanks @BruceForstall . Since the PR works, I will probably replace this PR with a one that has some relevant changes that we can test because if I merge this PR as is, it will kick off the CI runs in runtime repo which won't be useful at this point.

**Comment by BruceForstall** [comment]
> if I merge this PR as is, it will kick off the CI runs in runtime repo

Why is that? The runtime repo doesn't respond to changes in jitutils.

**Comment by kunalspathak** [comment]
> > if I merge this PR as is, it will kick off the CI runs in runtime repo
> 
> Why is that? The runtime repo doesn't respond to changes in jitutils.

Ah, never mind. I thought this approval was for https://github.com/BruceForstall/runtime/pull/1.

**Comment by AndyAyersMS** [comment]
Just some random thoughts...

Now that the altjit naming is systematic I wonder if we should add "wildcard" support, eg run batches of diffs using all known altjit os/isa combinations or something?

Also if/when a regular jit can run as an altjit some of the file swapping done by jit-dasm-pmi can be simplified as we no longer need to replace the "real jit" -- and once we do this we can perhaps also change the concurrently model for jit-dasm-pmi to be more like the one we use for crossgen (run base and diff tasks concurrently).

**Comment by kunalspathak** [comment]
> Now that the altjit naming is systematic I wonder if we should add "wildcard" support, eg run batches of diffs using all known altjit os/isa combinations or something?
> 
> Also if/when a regular jit can run as an altjit some of the file swapping done by jit-dasm-pmi can be simplified as we no longer need to replace the "real jit" -- and once we do this we can perhaps also change the concurrently model for jit-dasm-pmi to be more like the one we use for crossgen (run base and diff tasks concurrently).

I have opened https://github.com/dotnet/jitutils/issues/283 to track this.

**Comment by BruceForstall** [comment]
> if/when a regular jit can run as an altjit

I think we really need to remove altjit as a compile-time concept and move it to be a run-time concept. I really don't want the "cross" jits to be built and shipped as compile-time altjits for crossgen2.

I previously opened https://github.com/dotnet/runtime/issues/41643 to track this.

**Pull request merged**
