### PR TITLE
Update LLVM version to 13.0.1

### PR DESCRIPTION
**Pull request by echesakovMSFT**
* Use LLVM 13.0.1
* Use Visual Studio 2022 for building on Windows
* Use Ubuntu 18.04 containers for building on Linux

Work towards https://github.com/dotnet/jitutils/issues/349

### CODE REVIEW

**Comment by echesakovMSFT** [comment]
@BruceForstall PTAL

**Comment by BruceForstall** [comment]
Why not Ubuntu 20.04?

**Review by BruceForstall — APPROVED** [review]

**Comment by echesakovMSFT** [comment]
> Why not Ubuntu 20.04?

Isn't 18.04 still supported? We usually build Linux binaries on the oldest supported versions of the OS.

**Comment by BruceForstall** [comment]
> Isn't 18.04 still supported?

Yes, it is. 

> We usually build Linux binaries on the oldest supported versions of the OS.

That was my guess.

**Pull request merged**
