### PR TITLE
Add `--cross` arg; replace `--coreclr` with `--runtime`

### PR DESCRIPTION
**Pull request by BruceForstall**
Add a `--cross` argument for specifying to do cross compilation builds on Linux.

Replace the `--coreclr` argument with `--runtime`, to specify the root of the runtime repo.

Fix a minor bug where we output a lot of empty lines doing clang-tidy.

### CODE REVIEW

**Comment by BruceForstall** [comment]
This is a follow-up to https://github.com/dotnet/jitutils/pull/369

**Comment by BruceForstall** [comment]
This and https://github.com/dotnet/runtime/pull/92751 need to be merged at the same time.

**Comment by BruceForstall** [comment]
@kunalspathak @dotnet/jit-contrib PTAL
cc @sbomer

**Review by kunalspathak — APPROVED** [review]
LGTM

**Pull request merged**
