### PR TITLE
Add scripting to download xml config files.

### PR DESCRIPTION
**Pull request by jashook**
This will allow the coreclr xml files to be diffed. Note that
there is some timing that requires the ci generate job to have
run.

@RussKeldorph @mmitche ptal

The only issue this seems to have is every Http request requires an OAuth to Github which after 2k+ authenticated get requests I seem to be blocked by Github to authenticate further.

This keeps the script from finishing and requires you to wait about 30 minutes before continuing.

### CODE REVIEW

**Comment by jashook** [comment]
Also ptal @adiaaida 

/cc @russellhadley

**Comment by RussKeldorph** [comment]
@pgavlin 

I haven't looked in detail yet, but why is github required for this?  Shouldn't this all be queryable via unauth GET requests to Jenkins?  I'm sure I'm missing something obvious.

**Comment by jashook** [comment]
Jenkins considers the config.xml request to require authentication. If there is a way around this that I have not seen then I would love to know. It currently is quite a large downside.

**Comment by RussKeldorph** [comment]
Oh yeah, that's right.  You have to be auth'd to see the configure link.  Sorry I forgot about that.

**Comment by pgavlin** [comment]
What is in the config.xml files, and why do we need to be able to diff them?

**Comment by jashook** [comment]
The config files define each job's execution and all other properties. A no diff would prove that an old job will not be modified.

**Comment by pgavlin** [comment]
Okay. Seems fine to me, then.

**Pull request merged**
