### PR TITLE
Enable all AArch64 architecture features

### PR DESCRIPTION
**Pull request by BruceForstall**

### CODE REVIEW

**Comment by BruceForstall** [comment]
This allows JitLateDisasm to disassemble more SVE instructions than just those supported by Neoverse-N2. Last I looked, "+all" still had a bug such that it doesn't actually understand/disassemble *all* instructions, but it's much better.

**Review by a74nh — APPROVED** [review]
This looks like a good idea to me.

**Comment by BruceForstall** [comment]
Ping

**Review by kunalspathak — APPROVED** [review]
LGTM, sorry I forgot about this.

**Pull request merged**
