### PR TITLE
Bring over superpmicollect from coreclr/runtime repo

### PR DESCRIPTION
**Pull request by AndyAyersMS**
This is a pristine copy to use as a starting point for PMI/SPMI mashups.

### CODE REVIEW

**Comment by AndyAyersMS** [comment]
@BruceForstall PTAL
cc @dotnet/jit-contrib

**Comment by sandreenko** [comment]
Is the plane to keep https://github.com/dotnet/runtime/tree/master/src/coreclr/tests/src/JIT/superpmi in both runtime and jitutils?

Did @jashook use that cs logic for his OSX collection and replays or was it a separate python script?

**Comment by BruceForstall** [comment]
Can you pick up the changes I just merged as part of https://github.com/dotnet/runtime/pull/652?

Was this a pure copy (no change) of the version in the test tree?

I'm thinking that we'll want this functionality to be repackaged (eventually) as a library as part of the PMI/SuperPMI work, making this tool itself mostly a CLI on top of that library.

> Is the plan to keep https://github.com/dotnet/runtime/tree/master/src/coreclr/tests/src/JIT/superpmi in both runtime and jitutils?

IMO, yes. While it might be useful to have the runtime tests depend on jitutils packages (which currently aren't built), like it depends on coredistools, that might not be a dependency we want dotnet/runtime to have.

> Did @jashook use that cs logic for his OSX collection and replays or was it a separate python script?

A separate script: https://github.com/dotnet/runtime/blob/master/src/coreclr/scripts/superpmi.py. It was built using the same logic, though (and even copied the comments).

**Comment by AndyAyersMS** [comment]
> Was this a pure copy (no change) of the version in the test tree?

Yes, best to start off that way, I thought.

**Pull request merged**
