### PR TITLE
Update jitutils .NET Core SDK references

### PR DESCRIPTION
**Pull request by BruceForstall**
- Move from 3.0 to 3.1
- If 5.0 is installed, use that
- Stop building obsolete cijobs (I didn't want to delete it just yet; maybe
it could be repurposed for AzDO?)

### CODE REVIEW

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib Any comments?

**Comment by AndyAyersMS** [comment]
Do we know why `jit-includes` can't be pared down to just the "out-of-box" assemblies?

**Comment by BruceForstall** [comment]
> Do we know why jit-includes can't be pared down to just the "out-of-box" assemblies?

Well, I haven't tried to do that lately. There's System.CommandLine, of course, but I don't know about the others.

Maybe there was an interim state of 3.1 where all the right packages weren't available?

**Comment by BruceForstall** [comment]
I removed all the (now?) unnecessary assembly dependencies.

**Pull request merged**
